// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Действие documents */
interface ActionDocumentData {
  /**
   * title field in *Действие*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * link field in *Действие*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: action.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Действие document from Prismic
 *
 * - **API ID**: `action`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ActionDocumentData>, "action", Lang>;
/** Content for Автор documents */
interface AuthorDocumentData {
  /**
   * Имя field in *Автор*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField;
  /**
   * Должность field in *Автор*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  position: prismic.KeyTextField;
  /**
   * Фото field in *Автор*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  photo: prismic.ImageField<never>;
}
/**
 * Автор document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AuthorDocumentData>,
    "author",
    Lang
  >;
/** Content for Раздел documents */
type CategoryDocumentData = Record<string, never>;
/**
 * Раздел document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;
/** Content for Конфигурация documents */
interface ConfigDocumentData {
  /**
   * Логотип field in *Конфигурация*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: config.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<never>;
  /**
   * Кнопки в шапке field in *Конфигурация*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  buttons: prismic.GroupField<Simplify<ConfigDocumentDataButtonsItem>>;
  /**
   * Кнопки внизу field in *Конфигурация*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttonsbottom[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  buttonsbottom: prismic.GroupField<
    Simplify<ConfigDocumentDataButtonsbottomItem>
  >;
  /**
   * Показывать кнопку переключения темы field in *Конфигурация*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: config.isthemeswitchervisible
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  isthemeswitchervisible: prismic.BooleanField;
  /**
   * Slice Zone field in *Конфигурация*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: config.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ConfigDocumentDataSlicesSlice>;
}
/**
 * Item in Конфигурация → Кнопки в шапке
 *
 */
export interface ConfigDocumentDataButtonsItem {
  /**
   * Название кнопки field in *Конфигурация → Кнопки в шапке*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttons[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Тип кнопки field in *Конфигурация → Кнопки в шапке*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Ссылка field in *Конфигурация → Кнопки в шапке*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttons[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Размер кнопки field in *Конфигурация → Кнопки в шапке*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttons[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
}
/**
 * Item in Конфигурация → Кнопки внизу
 *
 */
export interface ConfigDocumentDataButtonsbottomItem {
  /**
   * Название кнопки field in *Конфигурация → Кнопки внизу*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttonsbottom[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Тип кнопки field in *Конфигурация → Кнопки внизу*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttonsbottom[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *Конфигурация → Кнопки внизу*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttonsbottom[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Ссылка field in *Конфигурация → Кнопки внизу*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: config.buttonsbottom[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Slice for *Конфигурация → Slice Zone*
 *
 */
type ConfigDocumentDataSlicesSlice = never;
/**
 * Конфигурация document from Prismic
 *
 * - **API ID**: `config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfigDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConfigDocumentData>,
    "config",
    Lang
  >;
/** Content for contact documents */
interface ContactDocumentData {
  /**
   * title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * link field in *contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * icon field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>;
}
/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Footer documents */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = FooterColumnSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;
/** Content for Меню documents */
interface MenuDocumentData {
  /**
   * menuItem field in *Меню*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menuitem[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menuitem: prismic.GroupField<Simplify<MenuDocumentDataMenuitemItem>>;
}
/**
 * Item in Меню → menuItem
 *
 */
export interface MenuDocumentDataMenuitemItem {
  /**
   * title field in *Меню → menuItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menuitem[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * icon field in *Меню → menuItem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menuitem[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>;
  /**
   * Страница field in *Меню → menuItem*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menuitem[].pageRelationshipField
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  pageRelationshipField: prismic.RelationField<"page">;
}
/**
 * Меню document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Страница documents */
interface PageDocumentData {
  /**
   * Адрес страницы field in *Страница*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /blog/post
   * - **API ID Path**: page.path
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  path: prismic.KeyTextField;
  /**
   * Выравнивание контента field in *Страница*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.align
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа">;
  /**
   * Показывать кнопку "Назад" field in *Страница*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.goback
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  goback: prismic.BooleanField;
  /**
   * Slice Zone field in *Страница*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * title field in *Страница*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * description field in *Страница*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismic.KeyTextField;
  /**
   * image field in *Страница*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Slice for *Страница → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | TextSlice
  | ImageWithCaptionSlice
  | HeaderWithLinkSlice
  | FaqSlice
  | VideoSlice
  | StatisticsSlice
  | FormSlice
  | GapSlice
  | AuthorSlice
  | BannerSlice
  | HeaderSlice
  | HeroSlice
  | ButtonsV2Slice
  | QuotesSlice
  | DividerSlice
  | ReviewsSmartWidgetsSlice
  | HeroVerticalSlice
  | CardsSlice
  | PostsSlice;
/**
 * Страница document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Услуга documents */
interface ProductDocumentData {
  /**
   * Название field in *Услуга*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Описание field in *Услуга*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Услуга document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;
export type AllDocumentTypes =
  | ActionDocument
  | AuthorDocument
  | CategoryDocument
  | ConfigDocument
  | ContactDocument
  | FooterDocument
  | MenuDocument
  | PageDocument
  | ProductDocument;
/**
 * Primary content in Author → Primary
 *
 */
interface AuthorSliceDefaultPrimary {
  /**
   * Автор field in *Author → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: author.primary.author
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  author: prismic.RelationField<"author">;
}
/**
 * Default variation for Author Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AuthorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AuthorSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Author*
 *
 */
type AuthorSliceVariation = AuthorSliceDefault;
/**
 * Author Shared Slice
 *
 * - **API ID**: `author`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AuthorSlice = prismic.SharedSlice<"author", AuthorSliceVariation>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface BannerSliceDefaultPrimary {
  /**
   * Заголовок field in *HeroBanner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: h1 для заголовка страницы
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Описание field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Введите описание
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Картинка field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Выравнивание field in *HeroBanner → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Выравнивание контента
   * - **API ID Path**: banner.primary.align
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа">;
  /**
   * Ширина field in *HeroBanner → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    "На всю ширину экрана" | "На всю ширину с отступами" | "Под размер текста"
  >;
}
/**
 * Item in HeroBanner → Items
 *
 */
export interface BannerSliceDefaultItem {
  /**
   * Название кнопки field in *HeroBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Введите название кнопки
   * - **API ID Path**: banner.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Тип кнопки field in *HeroBanner → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *HeroBanner → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Ссылка field in *HeroBanner → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  Simplify<BannerSliceDefaultItem>
>;
/**
 * Slice variation for *HeroBanner*
 *
 */
type BannerSliceVariation = BannerSliceDefault;
/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Primary content in Buttons → Primary
 *
 */
interface ButtonsV2SliceDefaultPrimary {
  /**
   * Ширина field in *Buttons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<"На всю ширину с отступами" | "Под размер текста">;
  /**
   * Выравнивание field in *Buttons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Слева
   * - **API ID Path**: buttons_v2.primary.align
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа", "filled">;
}
/**
 * Item in Buttons → Items
 *
 */
export interface ButtonsV2SliceDefaultItem {
  /**
   * Название field in *Buttons → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Ссылка field in *Buttons → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Тип кнопки field in *Buttons → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер field in *Buttons → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Иконка в начале field in *Buttons → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Material Symbols. Например: star
   * - **API ID Path**: buttons_v2.items[].starticon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  starticon: prismic.KeyTextField;
  /**
   * Иконка в конце field in *Buttons → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Material Symbols. Например: star
   * - **API ID Path**: buttons_v2.items[].endicon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  endicon: prismic.KeyTextField;
  /**
   * Действие field in *Buttons → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons_v2.items[].action
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  action: prismic.RelationField<"action">;
}
/**
 * Default variation for Buttons Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonsV2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ButtonsV2SliceDefaultPrimary>,
  Simplify<ButtonsV2SliceDefaultItem>
>;
/**
 * Slice variation for *Buttons*
 *
 */
type ButtonsV2SliceVariation = ButtonsV2SliceDefault;
/**
 * Buttons Shared Slice
 *
 * - **API ID**: `buttons_v2`
 * - **Description**: `ButtonsV2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonsV2Slice = prismic.SharedSlice<
  "buttons_v2",
  ButtonsV2SliceVariation
>;
/**
 * Primary content in Cards → Primary
 *
 */
interface CardsSliceDefaultPrimary {
  /**
   * Размер карточки field in *Cards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.primary.size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
}
/**
 * Item in Cards → Items
 *
 */
export interface CardsSliceDefaultItem {
  /**
   * Ссылка field in *Cards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Cards`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  Simplify<CardsSliceDefaultItem>
>;
/**
 * Slice variation for *Cards*
 *
 */
type CardsSliceVariation = CardsSliceDefault;
/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: `Cards`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;
/**
 * Primary content in Divider → Primary
 *
 */
interface DividerSliceDefaultPrimary {
  /**
   * Ширина field in *Divider → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: divider.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    "На всю ширину экрана" | "На всю ширину с отступами" | "Под размер текста"
  >;
}
/**
 * Default variation for Divider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DividerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DividerSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Divider*
 *
 */
type DividerSliceVariation = DividerSliceDefault;
/**
 * Divider Shared Slice
 *
 * - **API ID**: `divider`
 * - **Description**: `Divider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DividerSlice = prismic.SharedSlice<
  "divider",
  DividerSliceVariation
>;
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
  /**
   * Вопрос field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  question: prismic.KeyTextField;
  /**
   * Ответ field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  answer: prismic.RichTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FaqSliceDefaultItem>
>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in FooterColumn → Primary
 *
 */
interface FooterColumnSliceDefaultPrimary {
  /**
   * Название колонки field in *FooterColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Ссылка field in *FooterColumn → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Item in FooterColumn → Items
 *
 */
export interface FooterColumnSliceDefaultItem {
  /**
   * Название кнопки field in *FooterColumn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Ссылка field in *FooterColumn → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Тип кнопки field in *FooterColumn → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Иконка в начале field in *FooterColumn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.items[].starticon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  starticon: prismic.KeyTextField;
}
/**
 * Default variation for FooterColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterColumnSliceDefaultPrimary>,
  Simplify<FooterColumnSliceDefaultItem>
>;
/**
 * Slice variation for *FooterColumn*
 *
 */
type FooterColumnSliceVariation = FooterColumnSliceDefault;
/**
 * FooterColumn Shared Slice
 *
 * - **API ID**: `footer_column`
 * - **Description**: `FooterColumn`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterColumnSlice = prismic.SharedSlice<
  "footer_column",
  FooterColumnSliceVariation
>;
/**
 * Primary content in Form → Primary
 *
 */
interface FormSliceDefaultPrimary {
  /**
   * Название кнопки field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.buttontitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontitle: prismic.KeyTextField;
  /**
   * buttonVariant field in *Form → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.buttonvariant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  buttonvariant: prismic.SelectField<
    "filled" | "filledTonal" | "outlined" | "text"
  >;
}
/**
 * Item in Form → Items
 *
 */
export interface FormSliceDefaultItem {
  /**
   * title field in *Form → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * sliceExample field in *Form → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: form.items[].sliceexample
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  sliceexample: prismic.EmbedField;
}
/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Form`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  Simplify<FormSliceDefaultItem>
>;
/**
 * Slice variation for *Form*
 *
 */
type FormSliceVariation = FormSliceDefault;
/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: `Form`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;
/**
 * Primary content in Gap → Primary
 *
 */
interface GapSliceDefaultPrimary {
  /**
   * Размер field in *Gap → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: gap.primary.size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"s" | "m" | "l">;
}
/**
 * Default variation for Gap Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Gap`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GapSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Gap*
 *
 */
type GapSliceVariation = GapSliceDefault;
/**
 * Gap Shared Slice
 *
 * - **API ID**: `gap`
 * - **Description**: `Gap`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GapSlice = prismic.SharedSlice<"gap", GapSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeaderSliceDefaultPrimary {
  /**
   * Заголовок field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Если заголовок страницы, то h1
   * - **API ID Path**: header.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Описание field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Введите описание
   * - **API ID Path**: header.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Выравнивание field in *Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.align
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа">;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeaderSliceDefaultItem {
  /**
   * Название кнопки field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Введите название кнопки
   * - **API ID Path**: header.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Тип кнопки field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Ссылка field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  Simplify<HeaderSliceDefaultItem>
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeaderSliceVariation = HeaderSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;
/**
 * Primary content in SectionHeader → Primary
 *
 */
interface HeaderWithLinkSliceDefaultPrimary {
  /**
   * Заголовок field in *SectionHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Введите заголовок
   * - **API ID Path**: header_with_link.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Описание field in *SectionHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Введите описание
   * - **API ID Path**: header_with_link.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Item in SectionHeader → Items
 *
 */
export interface HeaderWithLinkSliceDefaultItem {
  /**
   * Название кнопки field in *SectionHeader → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_link.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Ссылка field in *SectionHeader → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_link.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Тип кнопки field in *SectionHeader → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_link.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *SectionHeader → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_link.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
}
/**
 * Default variation for SectionHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeaderWithLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderWithLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderWithLinkSliceDefaultPrimary>,
  Simplify<HeaderWithLinkSliceDefaultItem>
>;
/**
 * Slice variation for *SectionHeader*
 *
 */
type HeaderWithLinkSliceVariation = HeaderWithLinkSliceDefault;
/**
 * SectionHeader Shared Slice
 *
 * - **API ID**: `header_with_link`
 * - **Description**: `HeaderWithLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderWithLinkSlice = prismic.SharedSlice<
  "header_with_link",
  HeaderWithLinkSliceVariation
>;
/**
 * Primary content in HeroImage → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Заголовок field in *HeroImage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Описание field in *HeroImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Введите описание
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Изображение field in *HeroImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"mobile" | "tablet" | "laptop">;
  /**
   * Положение изображения field in *HeroImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageposition
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  imageposition: prismic.SelectField<"Справа" | "Слева">;
  /**
   * Положение изображения на экране тел field in *HeroImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.mobileimageposition
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  mobileimageposition: prismic.SelectField<
    "Сверху" | "Снизу" | "Не показывать"
  >;
  /**
   * Размер изображения field in *HeroImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageweight
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  imageweight: prismic.SelectField<"s" | "m" | "l">;
  /**
   * Выравнивание контента field in *HeroImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Слева
   * - **API ID Path**: hero.primary.align
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа", "filled">;
  /**
   * Ширина field in *HeroImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    "На всю ширину экрана" | "На всю ширину с отступами" | "Под размер текста"
  >;
}
/**
 * Item in HeroImage → Items
 *
 */
export interface HeroSliceDefaultItem {
  /**
   * Название кнопки field in *HeroImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Тип кнопки field in *HeroImage → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *HeroImage → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Ссылка field in *HeroImage → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for HeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;
/**
 * Slice variation for *HeroImage*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * HeroImage Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in HeroImageVertical → Primary
 *
 */
interface HeroVerticalSliceDefaultPrimary {
  /**
   * Заголовок field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Можно выбрать h1, h2 или h3
   * - **API ID Path**: hero_vertical.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Описание field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Изображение field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Ширина изображения field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    | "На всю ширину экрана"
    | "На всю ширину с отступами"
    | "Под размер текста"
    | "Авто"
  >;
  /**
   * Высота изображения field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.primary.imageheight
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  imageheight: prismic.SelectField<
    "Маленькая" | "Средняя" | "Большая" | "Полная"
  >;
  /**
   * Изображение внизу field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_vertical.primary.isimagebottom
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  isimagebottom: prismic.BooleanField;
  /**
   * Выравнивание контента field in *HeroImageVertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.primary.align
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  align: prismic.SelectField<"Слева" | "По центру" | "Справа">;
}
/**
 * Item in HeroImageVertical → Items
 *
 */
export interface HeroVerticalSliceDefaultItem {
  /**
   * Название кнопки field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Ссылка field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Тип кнопки field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<
    | "Выпуклая"
    | "Заполненная"
    | "Тональная"
    | "Контурная"
    | "Текстовая"
    | "Подчеркнутая"
  >;
  /**
   * Размер кнопки field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Иконка в начале field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].starticon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  starticon: prismic.KeyTextField;
  /**
   * Иконка в конце field in *HeroImageVertical → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_vertical.items[].endicon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  endicon: prismic.KeyTextField;
}
/**
 * Default variation for HeroImageVertical Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroVerticalSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroVerticalSliceDefaultPrimary>,
  Simplify<HeroVerticalSliceDefaultItem>
>;
/**
 * Slice variation for *HeroImageVertical*
 *
 */
type HeroVerticalSliceVariation = HeroVerticalSliceDefault;
/**
 * HeroImageVertical Shared Slice
 *
 * - **API ID**: `hero_vertical`
 * - **Description**: `HeroVertical`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroVerticalSlice = prismic.SharedSlice<
  "hero_vertical",
  HeroVerticalSliceVariation
>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageWithCaptionSliceDefaultPrimary {
  /**
   * Картинка field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Подпись field in *Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismic.KeyTextField;
  /**
   * Ширина field in *Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    "На всю ширину экрана" | "На всю ширину с отступами" | "Под размер текста"
  >;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithCaptionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Image*
 *
 */
type ImageWithCaptionSliceVariation = ImageWithCaptionSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image_with_caption`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSlice = prismic.SharedSlice<
  "image_with_caption",
  ImageWithCaptionSliceVariation
>;
/**
 * Primary content in LatestPosts → Primary
 *
 */
interface PostsSliceDefaultPrimary {
  /**
   * test field in *LatestPosts → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.primary.test
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  test: prismic.RichTextField;
}
/**
 * Default variation for LatestPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *LatestPosts*
 *
 */
type PostsSliceVariation = PostsSliceDefault;
/**
 * LatestPosts Shared Slice
 *
 * - **API ID**: `posts`
 * - **Description**: `Posts`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PostsSlice = prismic.SharedSlice<"posts", PostsSliceVariation>;
/**
 * Primary content in Quiz → Primary
 *
 */
interface QuizSliceDefaultPrimary {
  /**
   * Заголовок field in *Quiz → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Как внедрить раздельный сбор мусора
   * - **API ID Path**: quiz.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Описание field in *Quiz → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Пройди тест и узнай, как внедрить..
   * - **API ID Path**: quiz.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Картинка field in *Quiz → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for Quiz Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuizSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuizSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Quiz*
 *
 */
type QuizSliceVariation = QuizSliceDefault;
/**
 * Quiz Shared Slice
 *
 * - **API ID**: `quiz`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuizSlice = prismic.SharedSlice<"quiz", QuizSliceVariation>;
/**
 * Primary content in Quotes → Primary
 *
 */
interface QuotesSliceDefaultPrimary {
  /**
   * Размер карточки field in *Quotes → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.primary.size
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  size: prismic.SelectField<"Маленькая" | "Средняя" | "Большая" | "Огромная">;
  /**
   * Тип карточки field in *Quotes → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.primary.variant
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  variant: prismic.SelectField<"Обычная" | "Заполненная" | "Контурная">;
}
/**
 * Item in Quotes → Items
 *
 */
export interface QuotesSliceDefaultItem {
  /**
   * text field in *Quotes → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * author field in *Quotes → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.items[].author
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  author: prismic.RelationField<"author">;
}
/**
 * Default variation for Quotes Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuotesSliceDefaultPrimary>,
  Simplify<QuotesSliceDefaultItem>
>;
/**
 * Slice variation for *Quotes*
 *
 */
type QuotesSliceVariation = QuotesSliceDefault;
/**
 * Quotes Shared Slice
 *
 * - **API ID**: `quotes`
 * - **Description**: `Quotes`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuotesSlice = prismic.SharedSlice<"quotes", QuotesSliceVariation>;
/**
 * Primary content in ReviewsSmartWidgets → Primary
 *
 */
interface ReviewsSmartWidgetsSliceDefaultPrimary {
  /**
   * data-app field in *ReviewsSmartWidgets → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_smart_widgets.primary.dataapp
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  dataapp: prismic.KeyTextField;
}
/**
 * Default variation for ReviewsSmartWidgets Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsSmartWidgetsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSmartWidgetsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ReviewsSmartWidgets*
 *
 */
type ReviewsSmartWidgetsSliceVariation = ReviewsSmartWidgetsSliceDefault;
/**
 * ReviewsSmartWidgets Shared Slice
 *
 * - **API ID**: `reviews_smart_widgets`
 * - **Description**: `ReviewsSmartWidgets`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsSmartWidgetsSlice = prismic.SharedSlice<
  "reviews_smart_widgets",
  ReviewsSmartWidgetsSliceVariation
>;
/**
 * Item in Statistics → Items
 *
 */
export interface StatisticsSliceDefaultItem {
  /**
   * value field in *Statistics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.items[].value
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  value: prismic.KeyTextField;
  /**
   * Описание field in *Statistics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismic.KeyTextField;
}
/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Statistics`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StatisticsSliceDefaultItem>
>;
/**
 * Slice variation for *Statistics*
 *
 */
type StatisticsSliceVariation = StatisticsSliceDefault;
/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: `Statistics`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSlice = prismic.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
  /**
   * Content field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;
/**
 * Primary content in Video → Primary
 *
 */
interface VideoSliceDefaultPrimary {
  /**
   * Ссылка field in *Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://youtu.be/9V4Tl0dBkVE
   * - **API ID Path**: video.primary.url
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  url: prismic.KeyTextField;
  /**
   * Ширина field in *Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.width
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  width: prismic.SelectField<
    "На всю ширину экрана" | "На всю ширину с отступами" | "Под размер текста"
  >;
}
/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Video*
 *
 */
type VideoSliceVariation = VideoSliceDefault;
/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ActionDocumentData,
      ActionDocument,
      AuthorDocumentData,
      AuthorDocument,
      CategoryDocumentData,
      CategoryDocument,
      ConfigDocumentData,
      ConfigDocumentDataButtonsItem,
      ConfigDocumentDataButtonsbottomItem,
      ConfigDocumentDataSlicesSlice,
      ConfigDocument,
      ContactDocumentData,
      ContactDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocument,
      MenuDocumentData,
      MenuDocumentDataMenuitemItem,
      MenuDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      ProductDocumentData,
      ProductDocument,
      AllDocumentTypes,
      AuthorSliceDefaultPrimary,
      AuthorSliceDefault,
      AuthorSliceVariation,
      AuthorSlice,
      BannerSliceDefaultPrimary,
      BannerSliceDefaultItem,
      BannerSliceDefault,
      BannerSliceVariation,
      BannerSlice,
      ButtonsV2SliceDefaultPrimary,
      ButtonsV2SliceDefaultItem,
      ButtonsV2SliceDefault,
      ButtonsV2SliceVariation,
      ButtonsV2Slice,
      CardsSliceDefaultPrimary,
      CardsSliceDefaultItem,
      CardsSliceDefault,
      CardsSliceVariation,
      CardsSlice,
      DividerSliceDefaultPrimary,
      DividerSliceDefault,
      DividerSliceVariation,
      DividerSlice,
      FaqSliceDefaultItem,
      FaqSliceDefault,
      FaqSliceVariation,
      FaqSlice,
      FooterColumnSliceDefaultPrimary,
      FooterColumnSliceDefaultItem,
      FooterColumnSliceDefault,
      FooterColumnSliceVariation,
      FooterColumnSlice,
      FormSliceDefaultPrimary,
      FormSliceDefaultItem,
      FormSliceDefault,
      FormSliceVariation,
      FormSlice,
      GapSliceDefaultPrimary,
      GapSliceDefault,
      GapSliceVariation,
      GapSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceDefaultItem,
      HeaderSliceDefault,
      HeaderSliceVariation,
      HeaderSlice,
      HeaderWithLinkSliceDefaultPrimary,
      HeaderWithLinkSliceDefaultItem,
      HeaderWithLinkSliceDefault,
      HeaderWithLinkSliceVariation,
      HeaderWithLinkSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
      HeroVerticalSliceDefaultPrimary,
      HeroVerticalSliceDefaultItem,
      HeroVerticalSliceDefault,
      HeroVerticalSliceVariation,
      HeroVerticalSlice,
      ImageWithCaptionSliceDefaultPrimary,
      ImageWithCaptionSliceDefault,
      ImageWithCaptionSliceVariation,
      ImageWithCaptionSlice,
      PostsSliceDefaultPrimary,
      PostsSliceDefault,
      PostsSliceVariation,
      PostsSlice,
      QuizSliceDefaultPrimary,
      QuizSliceDefault,
      QuizSliceVariation,
      QuizSlice,
      QuotesSliceDefaultPrimary,
      QuotesSliceDefaultItem,
      QuotesSliceDefault,
      QuotesSliceVariation,
      QuotesSlice,
      ReviewsSmartWidgetsSliceDefaultPrimary,
      ReviewsSmartWidgetsSliceDefault,
      ReviewsSmartWidgetsSliceVariation,
      ReviewsSmartWidgetsSlice,
      StatisticsSliceDefaultItem,
      StatisticsSliceDefault,
      StatisticsSliceVariation,
      StatisticsSlice,
      TextSliceDefaultPrimary,
      TextSliceDefault,
      TextSliceVariation,
      TextSlice,
      VideoSliceDefaultPrimary,
      VideoSliceDefault,
      VideoSliceVariation,
      VideoSlice,
    };
  }
}
