// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  author: dynamic(() => import("./Author")),
  banner: dynamic(() => import("./Banner")),
  buttons_v2: dynamic(() => import("./Buttons")),
  cards: dynamic(() => import("./Cards")),
  divider: dynamic(() => import("./Divider")),
  faq: dynamic(() => import("./Faq")),
  footer_column: dynamic(() => import("./FooterColumn")),
  form: dynamic(() => import("./Form")),
  gap: dynamic(() => import("./Gap")),
  header: dynamic(() => import("./Header")),
  header_with_link: dynamic(() => import("./HeaderHorisontal")),
  hero: dynamic(() => import("./Hero")),
  image_with_caption: dynamic(() => import("./Image")),
  quiz: dynamic(() => import("./Quiz")),
  quotes: dynamic(() => import("./Quotes")),
  reviews_smart_widgets: dynamic(() => import("./ReviewsSmartWidgets")),
  statistics: dynamic(() => import("./Statistics")),
  text: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
};
